Update adafruit_as7341.py
adafruit/Adafruit_CircuitPython_AS7341 pull request #3
Opened 2020-12-07 21:25 UTC by DaveLangstaff

coerce new_current to between 0 and 127 to avoid wrap-around when led_current=0
avoids the unexpected result of led_current=0 producing maimum brightness

2020-12-11 17:56 UTC, siddacious commented
@DaveLangstaff Thanks for catching my bug!

The failing check is from the Black formatter; please use Black to format the code and we should be good to merge

This guide has info on using black:
https://learn.adafruit.com/improve-your-code-with-pylint

2020-12-11 18:00 UTC, siddacious requested changes
(repeated for mandatory change request comment):
Please format with Black

2020-12-20 15:52 UTC, adeanzan commented
Sorry for asking a possibly unrelated question in this PR, but I found it while trying to figure out how to turn off the LED. Will this change allow turning off the LED? 

I've tried this without success:

```
sensor = AS7341(i2c)

sensor.led = False
```

2021-01-24 02:59 UTC, caternuson commented
Closing. Fixed with #9.

2021-01-24 02:59 UTC, closed without merging